# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b11590942814c99d4a80e845b205813a"
name = "Test-assessment"
handle = "test-assessment-5"
application_url = "https://rome-holland-hospital-achieve.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"

[auth]
redirect_urls = [
  "https://rome-holland-hospital-achieve.trycloudflare.com/auth/callback",
  "https://rome-holland-hospital-achieve.trycloudflare.com/auth/shopify/callback",
  "https://rome-holland-hospital-achieve.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
